const constants = {
    GET_INTENTS: "GET_INTENT",
    GET_RESPONSE: "GET_RESPONSE",
    SWITCH_INTENT_SELECTION: "SWITCH_INTENT_SELECTION",
    USER_LOGGED_IN: "USER_LOGGED_IN",
    SWITCH_INTENT_VIEW: "SWITCH_INTENT_VIEW"
}

export default constants;